// Code generated by mockery v2.16.0. DO NOT EDIT.

package mock

import (
	context "context"
	entity "payment_processing_system/internal/domain/entity"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// BalanceStorage is an autogenerated mock type for the BalanceStorage type
type BalanceStorage struct {
	mock.Mock
}

// DecreaseAmount provides a mock function with given fields: ctx, id, amount
func (_m *BalanceStorage) DecreaseAmount(ctx context.Context, id int64, amount decimal.Decimal) error {
	ret := _m.Called(ctx, id, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, decimal.Decimal) error); ok {
		r0 = rf(ctx, id, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BalanceStorage) GetByID(ctx context.Context, id int64) (*entity.Balance, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Balance
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Balance); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Balance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncreaseAmount provides a mock function with given fields: ctx, id, amount
func (_m *BalanceStorage) IncreaseAmount(ctx context.Context, id int64, amount decimal.Decimal) error {
	ret := _m.Called(ctx, id, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, decimal.Decimal) error); ok {
		r0 = rf(ctx, id, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBalanceStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewBalanceStorage creates a new instance of BalanceStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBalanceStorage(t mockConstructorTestingTNewBalanceStorage) *BalanceStorage {
	mock := &BalanceStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
