// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package v1

import (
	"time"
)

// Defines values for GetBindedTransactionsParamsSort.
const (
	Amount GetBindedTransactionsParamsSort = "amount"
	Date   GetBindedTransactionsParamsSort = "date"
	Id     GetBindedTransactionsParamsSort = "id"
)

// Balance defines model for Balance.
type Balance struct {
	Amount string `json:"amount"`
	Id     int64  `json:"id"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// NewBalance defines model for NewBalance.
type NewBalance struct {
	Amount string `json:"amount"`
	Id     int64  `json:"id"`
}

// NewTransaction defines model for NewTransaction.
type NewTransaction struct {
	Amount          string    `json:"amount"`
	DateTimeCreated time.Time `json:"date_time_created"`
	DateTimeUpdated time.Time `json:"date_time_updated"`
	DestinationId   *int64    `json:"destination_id"`
	Id              uint64    `json:"id"`
	SourceId        *int64    `json:"source_id"`
	Status          string    `json:"status"`
	Ttype           string    `json:"ttype"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount          string    `json:"amount"`
	DateTimeCreated time.Time `json:"date_time_created"`
	DateTimeUpdated time.Time `json:"date_time_updated"`
	DestinationId   *int64    `json:"destination_id"`
	Id              uint64    `json:"id"`
	SourceId        *int64    `json:"source_id"`
	Status          string    `json:"status"`
	Ttype           string    `json:"ttype"`
}

// Transactions defines model for Transactions.
type Transactions = []struct {
	Amount          string    `json:"amount"`
	DateTimeCreated time.Time `json:"date_time_created"`
	DateTimeUpdated time.Time `json:"date_time_updated"`
	DestinationId   *int64    `json:"destination_id"`
	Id              uint64    `json:"id"`
	SourceId        *int64    `json:"source_id"`
	Status          string    `json:"status"`
	Ttype           string    `json:"ttype"`
}

// GetBalanceByIdParams defines parameters for GetBalanceById.
type GetBalanceByIdParams struct {
	// Currency Currency to display balance
	Currency *string `form:"currency,omitempty" json:"currency,omitempty"`
}

// GetBindedTransactionsParams defines parameters for GetBindedTransactions.
type GetBindedTransactionsParams struct {
	// Sort key to sort by - id, date, amount
	Sort *GetBindedTransactionsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Limit maximum number of results to return
	Limit *uint64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Page page of collection
	Page *uint64 `form:"page,omitempty" json:"page,omitempty"`
}

// GetBindedTransactionsParamsSort defines parameters for GetBindedTransactions.
type GetBindedTransactionsParamsSort string

// AccrueOrWriteOffBalanceJSONRequestBody defines body for AccrueOrWriteOffBalance for application/json ContentType.
type AccrueOrWriteOffBalanceJSONRequestBody = NewBalance
